version: '2'
services:
  src:
    image: project/src
    volumes:
      - /Users/VNHCLZ0191/Downloads/myproject:/var/www/project:rw
    privileged: true
  fpm:
    image: project/fpm-7
    volumes_from:
      - src
    privileged: true
  nginx:
    image: project/nginx-7
    volumes_from:
      - fpm
    links:
      - fpm:fpm
    ports:
      - "8080:80"
    privileged: true
volumes:
  src: {}
